theme:
  name: material
  palette:
    - scheme: default  # Light mode
      primary: blue
      accent: indigo
    - scheme: slate  # Dark mode
      primary: deep-purple
      accent: pink
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - content.code.copy  # Copy button for code
    - content.tooltips  # Hover tooltips for links
    - content.tabs  # Enables tabbed interface
  extra_css:
    - styles/custom.css
